name: Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Download current version
      uses: ambimax/action-setup-pulumi@develop
    - run: pulumi version

    - name: Download version 1.3.4
      uses: ambimax/action-setup-pulumi@develop
      with:
        version: 1.3.4
    - run: pulumi version
