name: Test

on:
  push:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: ambimax/action-setup-pulumi@develop
      with:
        version: 1.3.4

    - run: pulumi version
